name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar Gradle
      run: sudo apt-get update && sudo apt-get install -y gradle

    - name: Compilar el proyecto
      run: gradle build

    - name: Ejecutar HolaMundo
      run: java -cp build/classes/java/main HolaMundo
